# Generated by Django 4.1.5 on 2023-04-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0006_remove_cart_ordered_remove_cart_ordered_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite',
            name='slug',
            field=models.SlugField(default='', max_length=128, unique=True),
        ),
    ]
